version: '3.8'

services:
  prestashop:
    image: kequel/be-prestashop-196615:latest
    ports:
      - target: 443
        published: 19665
        protocol: tcp
        mode: host
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=admin-mysql_db
      - DB_NAME=BE_196615_prestashop
      - DB_USER=root
      - DB_PASSWORD=student
    networks:
      - default
      - admin-mysql_default
    deploy:
      placement:
        constraints:
          - node.hostname == student-swarm01
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - target: 8025
        published: 19666
        protocol: tcp
        mode: host
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.hostname == student-swarm01
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  default:
  admin-mysql_default:
    external: true
