version: '3.8'

services:
  prestashop:
    image: kequel/be-prestashop-196615:test
    ports:
      - "19661:80"
      - "19662:443"
    volumes:
      - prestashop_data:/var/www/html
    environment:
      DB_SERVER: student-swarm01.maas
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: student
      DB_NAME: BE_196615_prestashop
      PS_INSTALL_AUTO: '0'
      PS_DEV_MODE: 'false'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  mailhog:
    image: mailhog/mailhog
    ports:
      - "19663:1025"
      - "19664:8025"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

volumes:
  prestashop_data:
