COMPLETE_WINDOW_SLEEP_TIME = 1.5
COMPLETE_SECTION_SLEEP_TIME = 0.5
INTER_SLEEP_TIME = 0.2

URL = "https://localhost:8443/"

PRODUCTS_TO_BUY = 4     # TODO: zamienic na 10
PRODUCTS_TO_BUY_IN_THE_CATEGORY = int(PRODUCTS_TO_BUY / 2)